In [35]:
import numpy as np

data = np.loadtxt('data/chocolate_rating.csv', delimiter=',')
print(data)

[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]


In [39]:
rating_mean = data[:, 3].mean()
print(rating_mean)

3.185933147632312


In [41]:
high_level = data[data[:, 3] >= 4]
print(high_level)

[[1.000e+01 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+01 2.013e+03 7.000e-01 4.000e+00]
 [2.100e+01 2.013e+03 6.300e-01 4.000e+00]
 [5.500e+01 2.011e+03 7.000e-01 4.000e+00]
 [5.700e+01 2.010e+03 7.000e-01 4.000e+00]
 [7.700e+01 2.007e+03 7.000e-01 4.000e+00]
 [7.800e+01 2.007e+03 7.500e-01 4.000e+00]
 [7.900e+01 2.007e+03 7.000e-01 5.000e+00]
 [8.400e+01 2.007e+03 7.000e-01 4.000e+00]
 [8.700e+01 2.006e+03 7.000e-01 5.000e+00]
 [8.800e+01 2.006e+03 6.600e-01 4.000e+00]
 [9.300e+01 2.010e+03 6.000e-01 4.000e+00]
 [1.080e+02 2.016e+03 7.000e-01 4.000e+00]
 [1.090e+02 2.016e+03 7.000e-01 4.000e+00]
 [1.180e+02 2.015e+03 7.000e-01 4.000e+00]
 [1.240e+02 2.011e+03 7.200e-01 4.000e+00]
 [1.530e+02 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+02 2.013e+03 7.300e-01 4.000e+00]
 [1.810e+02 2.011e+03 7.200e-01 4.000e+00]
 [1.870e+02 2.011e+03 7.200e-01 4.000e+00]
 [2.230e+02 2.014e+03 7.500e-01 4.000e+00]
 [2.320e+02 2.011e+03 7.500e-01 4.000e+00]
 [2.330e+02 2.011e+03 7.500e-01 4.000e+00]
 [2.400e+02

In [42]:
high_id = data[:, 0].astype(int)
print(high_id)

[   1    2    3 ... 1793 1794 1795]


In [60]:
include_kakao = high_level[:, 2]
max_include = np.max(high_level[:, 2])

# 결과 출력
print("최대 함유량:", max_include)

frequency = np.count_nonzero(include_kakao == max_include)


print("빈도수:", frequency)

최대 함유량: 0.88
빈도수: 1
